version: '2.1'
services:
  mongodb:
    image: mongo:3.4
    container_name: mongo
    volumes:
      - /data/mongo:/data/db
    network_mode: host
    restart: always
  redis:
    image: redis:4.0.6
    container_name: redis
    volumes:
      - /data/redis:/data
    network_mode: host
    restart: always
  easymock:
    image: goodrainapps/easymock:v1.6.0
    container_name: easymock
    volumes:
      - /data/easymock/:/home/easy-mock/easy-mock/
    network_mode: host
    restart: always